"""init

Revision ID: 1e99c73a2dfb
Revises: 
Create Date: 2022-06-20 21:45:13.065130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e99c73a2dfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_data_permission',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('authorized_object_category', sa.String(length=255), nullable=False, comment='被授权实体类型'),
    sa.Column('authorized_object_id', sa.String(length=40), nullable=False, comment='被授权实体ID'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=True, comment='授权起始时间'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='授权起始时间'),
    sa.Column('permitted_object_category', sa.String(length=255), nullable=False, comment='授权项目类型'),
    sa.Column('permission_category', sa.String(length=255), nullable=False, comment='授权类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_data_permission_detail',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('data_permission_id', sa.String(length=40), nullable=False, comment='授权信息'),
    sa.Column('permitted_object_category', sa.String(length=255), nullable=False, comment='授权项目类型'),
    sa.Column('permitted_object_id', sa.String(length=40), nullable=False, comment='授权项目ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_master_organization',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('guest_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_master_people',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('team_id', sa.String(length=40), nullable=False, comment='代表队id'),
    sa.Column('team_group_id', sa.String(length=40), nullable=False, comment='参赛组id'),
    sa.Column('people_name', sa.String(length=255), nullable=True, comment='姓名'),
    sa.Column('people_gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('people_birth', sa.DateTime(timezone=True), nullable=True, comment='生日'),
    sa.Column('number_cloth_id', sa.Integer(), nullable=True, comment='号码布编号'),
    sa.Column('number_cloth', sa.String(length=20), nullable=True, comment='号码布'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_master_user',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('username', sa.String(length=40), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=40), nullable=False, comment='密码'),
    sa.Column('salt', sa.String(length=8), nullable=False, comment='盐'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('st_menu',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('parent_id', sa.String(length=40), nullable=True, comment='父项目'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='路由'),
    sa.Column('component', sa.String(length=255), nullable=False, comment='组件'),
    sa.Column('icon', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('title', sa.String(length=40), nullable=False, comment='标题'),
    sa.Column('name', sa.String(length=40), nullable=False, comment='代码'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('redirect', sa.String(length=255), nullable=True, comment='重定向'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='启用'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_role',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('role_name', sa.String(length=255), nullable=True, comment='角色名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='代码'),
    sa.Column('comment', sa.String(length=1000), nullable=True, comment='备注'),
    sa.Column('editable', sa.Boolean(), nullable=True, comment='可编辑'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='启用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user_organization_map',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('user_id', sa.String(length=40), nullable=False, comment='用户id'),
    sa.Column('organization_id', sa.String(length=40), nullable=False, comment='组织id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_organization_map_organization_id'), 'user_organization_map', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organization_map_user_id'), 'user_organization_map', ['user_id'], unique=True)
    op.create_table('user_role_map',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='版本'),
    sa.Column('user_id', sa.String(length=40), nullable=False, comment='用户id'),
    sa.Column('role_id', sa.String(length=40), nullable=False, comment='角色id'),
    sa.Column('last_enabled_time', sa.DateTime(timezone=True), nullable=True, comment='路由类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_map_role_id'), 'user_role_map', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_map_user_id'), 'user_role_map', ['user_id'], unique=False)
    op.create_table('unit_of_work',
    sa.Column('id', sa.String(length=40), nullable=False, comment='操作ID'),
    sa.Column('handler_category', sa.String(length=255), nullable=True, comment='操作人类型'),
    sa.Column('handler_id', sa.String(length=40), nullable=True, comment='操作人ID'),
    sa.Column('handled_begin_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='操作起始时间'),
    sa.Column('handled_end_at', sa.DateTime(timezone=True), nullable=True, comment='操作结束时间'),
    sa.Column('action', sa.String(length=255), nullable=True, comment='操作概述'),
    sa.Column('action_params', sa.Text(), nullable=True, comment='操作数据'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_area',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('parent_id', sa.String(length=40), nullable=True, comment='父节点'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('st_robot',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='代码'),
    sa.Column('permission_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('st_route',
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新于'),
    sa.Column('route_path', sa.String(length=255), nullable=False, comment='路由'),
    sa.Column('group', sa.String(length=255), nullable=True, comment='分组'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('need_login', sa.Boolean(), nullable=True, comment='需要登录'),
    sa.Column('allow_all', sa.Boolean(), nullable=True, comment='允许所有用户'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_path')
    )
    op.create_table('st_data_permission_detail_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('data_permission_id', sa.String(length=40), nullable=False, comment='授权信息'),
    sa.Column('permitted_object_category', sa.String(length=255), nullable=False, comment='授权项目类型'),
    sa.Column('permitted_object_id', sa.String(length=40), nullable=False, comment='授权项目ID'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_data_permission_detail_history_begin_transaction_id'), 'st_data_permission_detail_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_data_permission_detail_history_end_transaction_id'), 'st_data_permission_detail_history', ['end_transaction_id'], unique=False)
    op.create_table('st_data_permission_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('authorized_object_category', sa.String(length=255), nullable=False, comment='被授权实体类型'),
    sa.Column('authorized_object_id', sa.String(length=40), nullable=False, comment='被授权实体ID'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=True, comment='授权起始时间'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='授权起始时间'),
    sa.Column('permitted_object_category', sa.String(length=255), nullable=False, comment='授权项目类型'),
    sa.Column('permission_category', sa.String(length=255), nullable=False, comment='授权类型'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_data_permission_history_begin_transaction_id'), 'st_data_permission_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_data_permission_history_end_transaction_id'), 'st_data_permission_history', ['end_transaction_id'], unique=False)
    op.create_table('st_master_organization_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('guest_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_master_organization_history_begin_transaction_id'), 'st_master_organization_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_master_organization_history_end_transaction_id'), 'st_master_organization_history', ['end_transaction_id'], unique=False)
    op.create_table('st_master_people_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('team_id', sa.String(length=40), nullable=False, comment='代表队id'),
    sa.Column('team_group_id', sa.String(length=40), nullable=False, comment='参赛组id'),
    sa.Column('people_name', sa.String(length=255), nullable=True, comment='姓名'),
    sa.Column('people_gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('people_birth', sa.DateTime(timezone=True), nullable=True, comment='生日'),
    sa.Column('number_cloth_id', sa.Integer(), nullable=True, comment='号码布编号'),
    sa.Column('number_cloth', sa.String(length=20), nullable=True, comment='号码布'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_master_people_history_begin_transaction_id'), 'st_master_people_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_master_people_history_end_transaction_id'), 'st_master_people_history', ['end_transaction_id'], unique=False)
    op.create_table('st_master_user_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('username', sa.String(length=40), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=40), nullable=False, comment='密码'),
    sa.Column('salt', sa.String(length=8), nullable=False, comment='盐'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_master_user_history_begin_transaction_id'), 'st_master_user_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_master_user_history_end_transaction_id'), 'st_master_user_history', ['end_transaction_id'], unique=False)
    op.create_table('st_menu_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('parent_id', sa.String(length=40), nullable=True, comment='父项目'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='路由'),
    sa.Column('component', sa.String(length=255), nullable=False, comment='组件'),
    sa.Column('icon', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('title', sa.String(length=40), nullable=False, comment='标题'),
    sa.Column('name', sa.String(length=40), nullable=False, comment='代码'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('redirect', sa.String(length=255), nullable=True, comment='重定向'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='启用'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_menu_history_begin_transaction_id'), 'st_menu_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_menu_history_end_transaction_id'), 'st_menu_history', ['end_transaction_id'], unique=False)
    op.create_table('st_role_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('role_name', sa.String(length=255), nullable=True, comment='角色名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='代码'),
    sa.Column('comment', sa.String(length=1000), nullable=True, comment='备注'),
    sa.Column('editable', sa.Boolean(), nullable=True, comment='可编辑'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='启用'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_st_role_history_begin_transaction_id'), 'st_role_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_st_role_history_end_transaction_id'), 'st_role_history', ['end_transaction_id'], unique=False)
    op.create_table('user_organization_map_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('user_id', sa.String(length=40), nullable=False, comment='用户id'),
    sa.Column('organization_id', sa.String(length=40), nullable=False, comment='组织id'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_user_organization_map_history_begin_transaction_id'), 'user_organization_map_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_organization_map_history_end_transaction_id'), 'user_organization_map_history', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_organization_map_history_organization_id'), 'user_organization_map_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organization_map_history_user_id'), 'user_organization_map_history', ['user_id'], unique=False)
    op.create_table('user_role_map_history',
    sa.Column('history_id', sa.String(length=40), nullable=False, comment='history_id'),
    sa.Column('begin_at', sa.DateTime(timezone=True), nullable=False, comment='开始于'),
    sa.Column('begin_transaction_id', sa.String(length=40), nullable=True, comment='begin_transaction_id'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='结束于'),
    sa.Column('end_transaction_id', sa.String(length=40), nullable=True, comment='end_transaction_id'),
    sa.Column('id', sa.String(length=40), nullable=False, comment='id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本'),
    sa.Column('handler_category', sa.String(length=255), nullable=False, comment='更新者类型'),
    sa.Column('handler_id', sa.String(length=255), nullable=False, comment='更新者'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False, comment='更新于'),
    sa.Column('user_id', sa.String(length=40), nullable=False, comment='用户id'),
    sa.Column('role_id', sa.String(length=40), nullable=False, comment='角色id'),
    sa.Column('last_enabled_time', sa.DateTime(), nullable=True, comment='路由类型'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_user_role_map_history_begin_transaction_id'), 'user_role_map_history', ['begin_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_role_map_history_end_transaction_id'), 'user_role_map_history', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_role_map_history_role_id'), 'user_role_map_history', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_map_history_user_id'), 'user_role_map_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_map_history_user_id'), table_name='user_role_map_history')
    op.drop_index(op.f('ix_user_role_map_history_role_id'), table_name='user_role_map_history')
    op.drop_index(op.f('ix_user_role_map_history_end_transaction_id'), table_name='user_role_map_history')
    op.drop_index(op.f('ix_user_role_map_history_begin_transaction_id'), table_name='user_role_map_history')
    op.drop_table('user_role_map_history')
    op.drop_index(op.f('ix_user_organization_map_history_user_id'), table_name='user_organization_map_history')
    op.drop_index(op.f('ix_user_organization_map_history_organization_id'), table_name='user_organization_map_history')
    op.drop_index(op.f('ix_user_organization_map_history_end_transaction_id'), table_name='user_organization_map_history')
    op.drop_index(op.f('ix_user_organization_map_history_begin_transaction_id'), table_name='user_organization_map_history')
    op.drop_table('user_organization_map_history')
    op.drop_index(op.f('ix_st_role_history_end_transaction_id'), table_name='st_role_history')
    op.drop_index(op.f('ix_st_role_history_begin_transaction_id'), table_name='st_role_history')
    op.drop_table('st_role_history')
    op.drop_index(op.f('ix_st_menu_history_end_transaction_id'), table_name='st_menu_history')
    op.drop_index(op.f('ix_st_menu_history_begin_transaction_id'), table_name='st_menu_history')
    op.drop_table('st_menu_history')
    op.drop_index(op.f('ix_st_master_user_history_end_transaction_id'), table_name='st_master_user_history')
    op.drop_index(op.f('ix_st_master_user_history_begin_transaction_id'), table_name='st_master_user_history')
    op.drop_table('st_master_user_history')
    op.drop_index(op.f('ix_st_master_people_history_end_transaction_id'), table_name='st_master_people_history')
    op.drop_index(op.f('ix_st_master_people_history_begin_transaction_id'), table_name='st_master_people_history')
    op.drop_table('st_master_people_history')
    op.drop_index(op.f('ix_st_master_organization_history_end_transaction_id'), table_name='st_master_organization_history')
    op.drop_index(op.f('ix_st_master_organization_history_begin_transaction_id'), table_name='st_master_organization_history')
    op.drop_table('st_master_organization_history')
    op.drop_index(op.f('ix_st_data_permission_history_end_transaction_id'), table_name='st_data_permission_history')
    op.drop_index(op.f('ix_st_data_permission_history_begin_transaction_id'), table_name='st_data_permission_history')
    op.drop_table('st_data_permission_history')
    op.drop_index(op.f('ix_st_data_permission_detail_history_end_transaction_id'), table_name='st_data_permission_detail_history')
    op.drop_index(op.f('ix_st_data_permission_detail_history_begin_transaction_id'), table_name='st_data_permission_detail_history')
    op.drop_table('st_data_permission_detail_history')
    op.drop_table('st_route')
    op.drop_table('st_robot')
    op.drop_table('st_area')
    op.drop_table('unit_of_work')
    op.drop_index(op.f('ix_user_role_map_user_id'), table_name='user_role_map')
    op.drop_index(op.f('ix_user_role_map_role_id'), table_name='user_role_map')
    op.drop_table('user_role_map')
    op.drop_index(op.f('ix_user_organization_map_user_id'), table_name='user_organization_map')
    op.drop_index(op.f('ix_user_organization_map_organization_id'), table_name='user_organization_map')
    op.drop_table('user_organization_map')
    op.drop_table('st_role')
    op.drop_table('st_menu')
    op.drop_table('st_master_user')
    op.drop_table('st_master_people')
    op.drop_table('st_master_organization')
    op.drop_table('st_data_permission_detail')
    op.drop_table('st_data_permission')
    # ### end Alembic commands ###
